spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/carlist
    password: ''
  servlet:
    multipart:
      max-request-size: 2MB
      max-file-size: 2MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true '
server:
  port: '8089'